### ISSUE TITLE
Build failure with ghc 8.2: can't find spInfoName

### ISSUE THREAD

**Issue by DanBurton** [haskell-distributed/distributed-static#17]
As seen on the stackage build server:

```
[1 of 1] Compiling Control.Distributed.Static ( src/Control/Distributed/Static.hs, dist/build/Control/Distributed/Static.o )

src/Control/Distributed/Static.hs:262:20: error:
    Variable not in scope: spInfoName :: StaticPtrInfo -> [Char]
    |
262 |     "<<static " ++ spInfoName (staticPtrInfo ptr) ++ " :: " ++ show typ ++ ">>"
    |                    ^^^^^^^^^^
```

I was able to reproduce locally like so:

```
$ stack unpack distributed-static-0.3.7
$ cd distributed-static-0.3.7
$ << copy in the following stack.yaml >>
$ stack build
```

```yaml
# stack.yaml
resolver: nightly-2017-08-25
extra-deps:
- rank1dynamic-0.4.0
```
